### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ueda-masa** [ueda-masa/furima-40463#20]
#what
お世話になります
フリマアプリの挙動確認をお願いします
下記、必要情報になります。

自身のフリマアプリのURL | https://furima-40463.onrender.com

Basic認証のIDとパスワード |  　admin   /  1111
出品者用のメールアドレスとパスワード |  test@test.com     123456t
購入者用のメールアドレスとパスワード｜　test@akst.com　987654f

#why
フリマアプリの挙動確認のため。

以上、よろしくお願いします。

**Comment by mo1015** [comment]
@ueda-masa さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **発送までの日数は、「---、1\~2日で発送、2\~3日で発送、4\~7日で発送」の4項目が表示されること（--- は初期値として設定すること）**
不要な「\」を削除しましょう。
<img width="395" alt="スクリーンショット 2024-04-12 9 53 23" src="https://github.com/ueda-masa/furima-40463/assets/62644781/db08d849-f779-4fa5-8846-7a5af884ee70">

- [ ] **エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
「Phone number can't be blank」のエラーメッセージが重複しています。

- [ ] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
「都道府県」を入力しなくてもエラーメッセージが表示されず、購入もできてしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ueda-masa** [comment]
#what
お世話になります
レビュー内容を修正しましたので
フリマアプリの挙動確認をお願いします

#why
フリマアプリの挙動確認のため。

以上、よろしくお願いします。

**Comment by snkw-works** [comment]
@ueda-masa さん、修正とご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点については修正が確認できました。ありがとうございます。
引き続き修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]
#### 商品出品機能
- [ ] **エラーハンドリングによって出品ページに戻った場合でも、入力済みの項目（商品画像・販売手数料・販売利益以外）は消えないよう修正しましょう**
入力済みのカテゴリー・商品の状態・配送料の負担・発送元の地域・発送までの日数が消えてしまいます。

https://github.com/ueda-masa/furima-40463/assets/54050089/25680291-ba87-483a-b6a9-ba8e6ec9b6bc


#### 商品購入機能
- [ ] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができるよう修正しましょう**
「都道府県」を選択しているにも関わらず「Prefecture can't be blank」と表示され、購入ができない状態です。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ueda-masa** [comment]
#what
お世話になります
レビュー内容を修正しましたので
フリマアプリの挙動確認をお願いします

#why
フリマアプリの挙動確認のため。

以上、よろしくお願いします。

**Comment by snkw-works** [comment]
@ueda-masa さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
